### ISSUE TITLE
Error message: A problem occurred evaluating root project 'linux_distributions' 

### ISSUE THREAD

**Issue by Alecton4** [oracle/javavscode#158]
Here is the poped out error notification in VSCode:

```text
Project linux_distributions: A problem occurred evaluating root project 'linux_distributions'.
Process 'command '../../bin/plugins-info'' finished with non-zero exit value 127 (build.gradle:58): A problem occurred evaluating root project 'linux_distributions'.
Process 'command '../../bin/plugins-info'' finished with non-zero exit value 127 (build.gradle:58)
```

Here is the content in output panel:

<details>

```
Initiating server activation
Request to kill LSP server.
Cannot kill: current process is None
Launching Oracle Java SE Language Server with /home/az/.sdkman/candidates/java/current and userdir /home/az/.config/Code/User/workspaceStorage/9dbf87d34f0bcab3ede4beda3f928fa2/Oracle.oracle-java
LSP server launching: 1037
LSP server user directory: /home/az/.config/Code/User/workspaceStorage/9dbf87d34f0bcab3ede4beda3f928fa2/Oracle.oracle-java
java.net.UnknownHostException: az-P1-openSUSE: az-P1-openSUSE: Name or service not known
	at java.base/java.net.InetAddress.getLocalHost(InetAddress.java:1670)
	at org.netbeans.CLIHandler$2.run(CLIHandler.java:643)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1420)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2035)
Caused by: java.net.UnknownHostException: az-P1-openSUSE: Name or service not known
	at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:930)
	at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1543)
	at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:848)
	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1533)
	at java.base/java.net.InetAddress.getLocalHost(InetAddress.java:1665)
	... 5 more
Code Name                                          Version                               State    
-------------------------------------------------- ------------------------------------- ---------
org.netbeans.modules.options.java                  1.37                                  Enabled  
org.netbeans.modules.editor.settings.storage       1.75.0.1                              Enabled  
org.netbeans.modules.xml.xdm                       1.57.0.1                              Enabled  
org.netbeans.modules.csl.types                     1.23                                  Enabled  
org.netbeans.swing.plaf                            1.65                                  Enabled  
org.netbeans.modules.terminal                      1.50                                  Enabled  
org.netbeans.modules.gradle.dependencies           1.0.0.1.1                             Enabled  
org.netbeans.modules.editor.document               1.32.0.3                              Enabled  
org.netbeans.modules.extexecution                  1.72                                  Enabled  
org.netbeans.api.java                              1.89                                  Enabled  
org.netbeans.modules.languages.antlr               1.5                                   Enabled  
org.netbeans.modules.project.ant.ui                1.88                                  Enabled  
org.netbeans.html.presenters.spi                   1.8.1                                 Enabled  
org.netbeans.modules.options.api                   1.68                                  Enabled  
org.netbeans.modules.maven.refactoring             1.43.1                                Enabled  
org.openide.modules                                7.71                                  Enabled  
org.netbeans.modules.editor.guards                 1.56                                  Enabled  
org.netbeans.spi.tasklist                          1.58.0.1                              Enabled  
org.netbeans.modules.html.parser                   1.57.0.1                              Enabled  
org.netbeans.modules.javascript2.debug             1.41                                  Enabled  
org.netbeans.lib.nbjavac                           1.39.0.4.3                            Enabled  
org.netbeans.modules.nbcode.integration            1.0                                   Enabled  
org.netbeans.modules.maven.persistence             1.52                                  Enabled  
org.netbeans.libs.graalsdk.system                  1.22                                  Installed
org.openide.util.lookup                            8.57                                  Enabled  
org.netbeans.modules.maven                         2.162.0.1.1                           Enabled  
org.netbeans.modules.masterfs.nio2                 1.38                                  Enabled  
org.netbeans.modules.javascript2.lexer             1.29                                  Enabled  
org.netbeans.modules.debugger.jpda.projectsui      1.26                                  Enabled  
org.netbeans.modules.web.common                    1.122                                 Enabled  
org.netbeans.modules.java.openjdk.project          1.20                                  Enabled  
org.netbeans.api.annotations.common                1.51                                  Enabled  
org.netbeans.modules.nativeimage.api               0.15                                  Enabled  
org.netbeans.modules.testng.ui                     1.32                                  Enabled  
org.netbeans.core.netigso                          1.54                                  Enabled  
org.netbeans.libs.jna.platform                     2.18                                  Enabled  
org.netbeans.modules.refactoring.api               1.70.0.1                              Enabled  
org.netbeans.api.xml.ui                            1.67                                  Enabled  
org.netbeans.modules.server                        1.56                                  Enabled  
org.netbeans.libs.jaxb                             1.54                                  Installed
org.netbeans.modules.gradle.test                   1.19                                  Enabled  
org.openide.execution                              9.26                                  Enabled  
org.netbeans.modules.htmlui                        1.8                                   Installed
org.netbeans.modules.classfile                     1.75                                  Enabled  
org.netbeans.modules.gsf.codecoverage              1.55                                  Installed
org.netbeans.spi.quicksearch                       1.50                                  Enabled  
org.netbeans.modules.java.guards                   0.54                                  Installed
org.openide.windows                                6.100                                 Enabled  
org.apache.commons.logging                         1.3.0                                 Enabled  
org.netbeans.modules.xml.multiview                 1.61.0.2                              Installed
org.netbeans.modules.html                          1.84                                  Installed
org.netbeans.modules.sampler                       1.37                                  Enabled  
org.netbeans.modules.java.sourceui                 1.71.0.2.4.3.32.6                     Enabled  
org.netbeans.modules.gototest                      1.57                                  Enabled  
org.netbeans.modules.editor.deprecated.pre65format 1.54.0.1.6.23.55                      Enabled  
org.netbeans.modules.templates                     1.30                                  Enabled  
org.netbeans.modules.xml.xam                       1.55.0.1                              Enabled  
org.netbeans.modules.editor.errorstripe            2.57.0.1.1                            Enabled  
org.netbeans.modules.project.libraries.ui          1.75                                  Enabled  
org.netbeans.modules.projectapi                    1.94                                  Enabled  
org.eclipse.jgit                                   6.8.0                                 Installed
org.netbeans.modules.schema2beans                  1.70                                  Installed
org.netbeans.modules.javadoc                       1.78.0.2                              Enabled  
slf4j.api                                          1.7.36                                Enabled  
org.openide.actions                                6.62                                  Enabled  
org.netbeans.modules.java.source                   0.188.0.32.4.3.6.1                    Enabled  
org.netbeans.modules.editor                        1.110.0.6.3.23.55                     Enabled  
org.netbeans.modules.selenium2.webclient           1.30                                  Installed
org.netbeans.modules.javascript2.model             1.29                                  Enabled  
org.openide.loaders                                7.93                                  Enabled  
org.netbeans.modules.versioning.core               1.54.0.1.42                           Installed
org.openide.nodes                                  7.68                                  Enabled  
org.netbeans.modules.java.debug                    1.61.0.1.3.6                          Enabled  
org.netbeans.modules.keyring.fallback              1.31                                  Enabled  
org.netbeans.swing.outline                         1.57                                  Enabled  
org.netbeans.modules.versioning                    1.70.0.1                              Installed
com.jcraft.jsch                                    0.1.72                                Installed
org.netbeans.modules.languages.yaml                2.55                                  Enabled  
org.openide.io                                     1.72                                  Enabled  
org.netbeans.modules.projectuiapi.base             1.109.0.9                             Enabled  
org.netbeans.libs.antlr3.runtime                   1.44.0.1                              Enabled  
org.netbeans.modules.editor.codetemplates          1.67.0.1                              Enabled  
org.netbeans.api.xml                               1.67                                  Enabled  
org.netbeans.modules.java.testrunner               1.43                                  Enabled  
org.netbeans.modules.maven.junit                   1.57                                  Enabled  
net.java.html.geo                                  1.8.1                                 Installed
org.netbeans.libs.testng                           1.37                                  Enabled  
org.netbeans.modules.java.disco                    2.7                                   Enabled  
org.netbeans.modules.j2ee.persistenceapi           1.59.0.1                              Enabled  
org.netbeans.libs.jsch.agentproxy                  1.7                                   Installed
org.netbeans.libs.asm                              5.26                                  Enabled  
org.netbeans.lib.v8debug                           1.39                                  Installed
org.netbeans.libs.flatlaf                          1.17                                  Enabled  
org.netbeans.modules.masterfs.linux                1.36                                  Enabled  
org.netbeans.modules.favorites                     1.69                                  Enabled  
org.netbeans.modules.gradle.persistence            1.19                                  Enabled  
org.netbeans.modules.maven.indexer.ui              2.57                                  Enabled  
org.netbeans.modules.db.metadata.model             1.34                                  Enabled  
org.netbeans.modules.options.keymap                1.60                                  Enabled  
org.netbeans.modules.project.spi.intern            1.26                                  Enabled  
org.netbeans.modules.project.indexingbridge        1.40                                  Enabled  
org.apache.commons.commons_io                      2.14                                  Enabled  
org.netbeans.libs.nbjavacapi                       21.1                                  Enabled  
org.netbeans.modules.queries                       1.66                                  Enabled  
org.netbeans.modules.libs.corba.omgapi             1.18                                  Enabled  
org.netbeans.modules.project.ant                   1.90                                  Enabled  
org.netbeans.modules.javascript2.doc               1.23                                  Enabled  
org.netbeans.modules.editor.mimelookup             1.63                                  Enabled  
org.netbeans.modules.editor.indent.project         1.45                                  Enabled  
org.netbeans.modules.java.lexer                    1.59                                  Enabled  
org.netbeans.spi.editor.hints                      1.65.0.8.55                           Enabled  
org.netbeans.modules.html.editor.lib               3.55                                  Enabled  
org.netbeans.modules.projectui                     1.82.0.8.9                            Enabled  
org.netbeans.modules.javascript2.editor            0.98                                  Enabled  
org.netbeans.spi.viewmodel                         1.74                                  Enabled  
org.netbeans.modules.web.indent                    1.43                                  Installed
org.netbeans.modules.progress.ui                   1.56                                  Enabled  
org.netbeans.modules.junitlib                      1.28                                  Enabled  
org.netbeans.modules.masterfs.ui                   2.26.0.2                              Enabled  
org.netbeans.modules.maven.junit.ui                1.28                                  Enabled  
org.netbeans.modules.lexer.antlr4                  1.5.0.1                               Enabled  
org.netbeans.modules.java.editor.base              2.88.0.1                              Enabled  
org.netbeans.core.multiview                        1.67                                  Enabled  
org.netbeans.modules.languages.toml                1.5                                   Enabled  
org.netbeans.modules.j2ee.eclipselinkmodelgen      1.55                                  Enabled  
org.netbeans.modules.code.analysis                 1.49                                  Enabled  
org.netbeans.modules.parsing.indexing              9.32.0.1.3.8                          Enabled  
org.netbeans.spi.debugger.ui                       2.81                                  Enabled  
net.java.html.boot.fx                              1.8.1                                 Installed
org.netbeans.modules.java.project                  1.95                                  Enabled  
org.netbeans.libs.lucene                           3.42                                  Enabled  
org.netbeans.modules.keyring.impl                  1.47                                  Enabled  
org.netbeans.modules.java.api.common               1.146                                 Enabled  
org.openide.explorer                               6.85                                  Enabled  
org.netbeans.modules.j2ee.persistence              1.78.0.1                              Installed
org.netbeans.modules.whitelist                     1.46                                  Enabled  
org.netbeans.modules.projectapi.nb                 1.27                                  Enabled  
org.openide.filesystems.compat8                    9.32                                  Enabled  
org.netbeans.modules.project.libraries             1.76                                  Enabled  
org.netbeans.modules.java.project.ui               1.98                                  Enabled  
libs.c.kohlschutter.junixsocket                    3.5                                   Installed
org.netbeans.modules.maven.embedder                2.78                                  Enabled  
org.netbeans.modules.html.lexer                    1.61                                  Enabled  
org.netbeans.core.osgi                             1.45                                  Installed
org.netbeans.libs.batik.read                       1.18.0.1                              Enabled  
org.netbeans.modules.java.hints.declarative        1.43.0.1.17.13                        Enabled  
org.netbeans.modules.netbinox                      1.64                                  Enabled  
org.netbeans.modules.selenium2.server              1.26                                  Enabled  
org.netbeans.modules.editor.structure              1.70.0.1                              Enabled  
org.netbeans.modules.parsing.lucene                2.59.0.1                              Enabled  
org.netbeans.modules.java.source.base              2.65.0.6.4.3.8.1                      Enabled  
org.netbeans.libs.graaljs                          1.23                                  Enabled  
org.netbeans.api.lsp                               1.24                                  Enabled  
org.netbeans.core.ui                               1.68                                  Enabled  
org.netbeans.modules.maven.model                   1.67                                  Enabled  
org.netbeans.modules.editor.bracesmatching         1.62.0.55                             Enabled  
org.apache.commons.lang3                           3.14.0                                Enabled  
org.netbeans.core.startup.base                     1.85.0.1                              Enabled  
org.netbeans.modules.textmate.lexer                1.23.0.1                              Enabled  
org.netbeans.libs.json_simple                      0.35                                  Enabled  
org.netbeans.modules.maven.indexer                 2.63                                  Enabled  
org.netbeans.modules.html.indexing                 1.15                                  Installed
org.netbeans.modules.project.dependency            1.7.0.1                               Enabled  
org.netbeans.libs.junit4                           1.41                                  Enabled  
org.netbeans.libs.junit5                           1.20                                  Installed
org.netbeans.libs.javacapi                         8.47.0.3                              Enabled  
org.netbeans.modules.defaults                      1.54                                  Enabled  
org.apache.xml.resolver                            1.54.0.12                             Enabled  
org.netbeans.modules.web.browser.api               1.68                                  Installed
org.netbeans.modules.autoupdate.services           1.79                                  Enabled  
org.netbeans.modules.editor.settings.lib           1.74.0.1                              Enabled  
org.netbeans.modules.selenium2                     1.28                                  Enabled  
org.netbeans.modules.debugger.jpda.truffle         1.20                                  Enabled  
org.netbeans.modules.extexecution.process          1.50                                  Enabled  
org.netbeans.modules.xml.catalog                   3.27.0.4                              Enabled  
org.netbeans.modules.java.source.ant               1.54.0.1.6                            Enabled  
org.netbeans.libs.snakeyaml_engine                 2.12                                  Enabled  
org.netbeans.core.network                          1.35                                  Enabled  
org.netbeans.spi.debugger.jpda.ui                  3.26                                  Enabled  
org.netbeans.modules.lexer.nbbridge                1.55.0.1                              Enabled  
org.netbeans.api.search                            1.44                                  Enabled  
org.netbeans.modules.java.platform.ui              1.65                                  Enabled  
org.openide.filesystems.nb                         9.33                                  Enabled  
org.netbeans.modules.keyring                       1.47                                  Enabled  
org.netbeans.api.templates                         1.31                                  Enabled  
org.netbeans.modules.csl.api                       2.81.0.2.1.1.8.1                      Enabled  
org.netbeans.modules.javaee.injection              1.29                                  Enabled  
org.netbeans.spi.palette                           1.69                                  Installed
org.netbeans.swing.laf.flatlaf                     1.16                                  Enabled  
org.netbeans.libs.truffleapi                       1.23                                  Enabled  
org.netbeans.modules.autoupdate.cli                1.37                                  Enabled  
org.netbeans.spi.navigator                         1.61                                  Enabled  
org.netbeans.modules.uihandler                     2.58                                  Installed
org.netbeans.modules.parsing.nb                    1.27.0.8.1                            Enabled  
org.netbeans.modules.properties.syntax             1.73                                  Enabled  
org.netbeans.modules.janitor                       1.16                                  Installed
org.eclipse.jgit.lfs                               6.8.0                                 Installed
org.netbeans.modules.templatesui                   1.26                                  Installed
org.netbeans.libs.git                              1.58                                  Installed
org.eclipse.jgit.gpg.bc                            6.8.0                                 Installed
org.netbeans.spi.java.hints                        1.57.0.13.4.3.32.6.8                  Enabled  
org.netbeans.modules.javascript2.types             1.23                                  Enabled  
org.netbeans.modules.web.common.ui                 1.24                                  Installed
org.netbeans.modules.debugger.jpda                 1.132.0.80                            Enabled  
org.netbeans.bootstrap                             2.102                                 Enabled  
org.netbeans.modules.java.source.queries           1.41                                  Installed
org.netbeans.modules.refactoring.java              1.85.0.1.3                            Enabled  
org.netbeans.modules.properties                    1.78                                  Enabled  
org.netbeans.modules.javascript2.json              1.26                                  Enabled  
org.netbeans.modules.print                         7.49                                  Enabled  
org.netbeans.modules.j2ee.metadata.model.support   1.54                                  Enabled  
org.netbeans.modules.debugger.jpda.ui              1.77                                  Enabled  
com.jcraft.jzlib                                   1.1.3                                 Installed
org.netbeans.libs.freemarker                       2.57.0.239                            Enabled  
org.openide.util                                   9.31                                  Enabled  
org.netbeans.modules.spi.actions                   1.51                                  Installed
org.netbeans.core.ide                              1.64                                  Enabled  
org.netbeans.modules.editor.breadcrumbs            1.40                                  Enabled  
org.netbeans.modules.editor.indent                 1.66                                  Enabled  
org.netbeans.modules.java.preprocessorbridge       1.72.0.1                              Enabled  
org.netbeans.modules.editor.actions                1.54.0.55                             Enabled  
org.apache.commons.codec                           1.16.0                                Enabled  
org.netbeans.api.debugger.jpda                     3.33                                  Enabled  
org.netbeans.core.io.ui                            1.53                                  Enabled  
org.netbeans.libs.tomlj                            1.5                                   Enabled  
org.netbeans.html.xhr4j                            1.8.1                                 Enabled  
org.netbeans.api.progress.compat8                  1.70                                  Installed
org.openide.dialogs                                7.70                                  Enabled  
org.netbeans.modules.xml.jaxb.api                  1.49                                  Installed
org.netbeans.modules.junit                         2.97                                  Enabled  
org.netbeans.modules.projectuiapi                  1.112.0.8                             Enabled  
org.netbeans.libs.nashorn                          3.4                                   Enabled  
org.netbeans.modules.gsf.testrunner.ui             1.38.0.1                              Enabled  
org.netbeans.modules.gradle                        2.38                                  Enabled  
org.openide.awt                                    7.91                                  Enabled  
org.netbeans.modules.j2ee.metadata                 1.55                                  Enabled  
org.netbeans.modules.gradle.editor                 1.5                                   Enabled  
org.netbeans.modules.java.j2seplatform             1.66                                  Enabled  
org.netbeans.modules.debugger.jpda.projects        1.63                                  Enabled  
org.netbeans.modules.java.lsp.server               2.6.0.1.2.12.1.17.32.6.2.8.1.8.1.1.13 Enabled  
org.netbeans.modules.editor.settings               1.80                                  Enabled  
org.netbeans.api.io                                1.26                                  Enabled  
org.netbeans.api.intent                            1.25                                  Enabled  
org.netbeans.modules.java.testrunner.ui            1.27                                  Enabled  
org.netbeans.modules.testng                        2.43                                  Enabled  
org.netbeans.api.progress.nb                       1.71                                  Enabled  
org.netbeans.modules.xml.text                      1.82.0.1                              Enabled  
com.google.gson                                    2.8.9                                 Enabled  
org.netbeans.modules.java.completion               2.9.0.2                               Enabled  
org.netbeans.modules.options.editor                1.83                                  Enabled  
net.java.html.sound                                1.8.1                                 Installed
org.netbeans.api.progress                          1.71                                  Enabled  
org.openide.util.ui                                9.32                                  Enabled  
org.netbeans.modules.junit.ui                      1.30                                  Enabled  
org.netbeans.modules.editor.fold                   1.68                                  Enabled  
org.netbeans.modules.java.source.queriesimpl       1.40                                  Installed
com.google.guava.failureaccess                     1.0.2                                 Enabled  
org.netbeans.modules.maven.hints                   1.63                                  Enabled  
org.netbeans.modules.editor.fold.nbui              1.35.0.55                             Enabled  
org.openide.util.ui.svg                            1.17                                  Enabled  
org.netbeans.libs.javafx                           2.30                                  Installed
org.netbeans.modules.editor.completion             1.68.0.2                              Enabled  
org.openide.text                                   6.91                                  Enabled  
org.netbeans.modules.jumpto                        1.78.0.1                              Enabled  
org.netbeans.modules.java.nativeimage.debugger     0.13                                  Enabled  
org.netbeans.modules.xml.lexer                     1.53                                  Enabled  
org.netbeans.modules.xml.core                      1.66.0.4                              Enabled  
org.netbeans.libs.osgi                             1.45                                  Enabled  
org.apache.tools.ant.module                        3.107.0.2                             Enabled  
org.netbeans.modules.java.mx.project               1.12                                  Enabled  
net.java.html.json                                 1.8.1                                 Enabled  
org.netbeans.core.startup                          1.86.0.1                              Enabled  
org.netbeans.modules.diff                          1.74.0.42.1                           Enabled  
org.netbeans.api.java.classpath                    1.77                                  Enabled  
org.netbeans.modules.lexer                         1.86.0.1                              Enabled  
org.netbeans.libs.jcodings                         0.12                                  Enabled  
org.netbeans.libs.commons_compress                 0.29.0.181                            Enabled  
org.netbeans.core.execution                        1.65                                  Enabled  
org.netbeans.modules.java.platform                 1.65                                  Enabled  
org.netbeans.modules.updatecenters                 1.63                                  Enabled  
org.netbeans.modules.swing.validation              1.55                                  Enabled  
org.netbeans.modules.java.hints.legacy.spi         1.40.0.1.13                           Enabled  
org.netbeans.swing.laf.dark                        2.18.0.2                              Installed
org.netbeans.core                                  3.74                                  Enabled  
org.netbeans.modules.sendopts                      2.59                                  Enabled  
org.netbeans.modules.java.hints                    1.106.0.17.3.12.1.1.32.6.1.1.13       Enabled  
net.java.html.boot                                 1.8.1                                 Enabled  
net.java.html.boot.script                          1.8.1                                 Installed
org.netbeans.modules.java.editor                   2.91.0.12.1.1.1                       Enabled  
org.netbeans.modules.java.file.launcher            1.0                                   Enabled  
org.netbeans.modules.editor.util                   1.88                                  Enabled  
org.eclipse.jgit.ssh.jsch                          6.8.0                                 Installed
org.netbeans.modules.gradle.dists                  1.11                                  Enabled  
org.netbeans.modules.javascript.v8debug            1.33.0.1                              Installed
com.google.guava                                   32.1.2                                Enabled  
org.netbeans.libs.antlr4.runtime                   1.24.0.1                              Enabled  
org.netbeans.libs.graalsdk                         1.23                                  Enabled  
org.netbeans.modules.dbschema                      1.64.0.4.30                           Enabled  
org.netbeans.api.maven                             1.29                                  Installed
org.netbeans.modules.settings                      1.72                                  Enabled  
org.netbeans.modules.editor.errorstripe.api        2.55.0.1                              Enabled  
org.netbeans.modules.masterfs                      2.78.0.2                              Enabled  
org.netbeans.lib.uihandler                         1.68                                  Installed
slf4j.jdk14                                        1.7.36                                Enabled  
org.netbeans.modules.markdown                      1.11                                  Enabled  
net.java.html                                      1.8.1                                 Enabled  
org.netbeans.modules.db                            1.92.0.30                             Enabled  
org.netbeans.modules.editor.lib                    4.30.0.23.3.55                        Enabled  
org.netbeans.modules.extexecution.process.jdk9     1.23                                  Enabled  
org.netbeans.modules.editor.mimelookup.impl        1.55                                  Enabled  
org.netbeans.modules.db.sql.editor                 1.60.0.30                             Installed
org.openide.filesystems                            9.36                                  Enabled  
org.netbeans.modules.editor.indent.support         1.65                                  Enabled  
org.netbeans.api.scripting                         1.20                                  Enabled  
org.netbeans.modules.libs.gradle                   8.6                                   Enabled  
org.netbeans.libs.flexmark                         1.16                                  Enabled  
org.netbeans.modules.extexecution.base             1.29                                  Enabled  
org.netbeans.api.htmlui                            1.31                                  Enabled  
org.netbeans.swing.tabcontrol                      1.80                                  Enabled  
org.netbeans.modules.editor.tools.storage          1.31                                  Enabled  
org.netbeans.modules.j2ee.core.utilities           1.57                                  Installed
org.netbeans.modules.gsf.testrunner                2.35                                  Enabled  
org.netbeans.libs.jna                              2.18                                  Enabled  
org.netbeans.modules.j2ee.eclipselink              1.55                                  Installed
org.netbeans.html.ko4j                             1.8.1                                 Enabled  
org.netbeans.modules.gradle.java                   1.25.0.1.1                            Enabled  
org.netbeans.modules.editor.lib2                   2.43.0.55.3                           Enabled  
com.googlecode.javaewah.JavaEWAH                   1.1.6                                 Installed
org.netbeans.modules.javahelp                      2.64                                  Enabled  
org.netbeans.modules.css.lib                       2.3                                   Enabled  
org.netbeans.api.debugger                          1.78                                  Enabled  
org.netbeans.modules.parsing.api                   9.30.0.8                              Enabled  
-------------------------------------------------- ------------------------------------- ---------
```

</details>

My environment:
- Operating System: openSUSE Tumbleweed 20240503
- Kernel Version: 6.8.8-1-default (64-bit)
- Java: OpenJDK Runtime Environment Temurin-11.0.23+9 (build 11.0.23+9) managed by [SDKMAN](https://sdkman.io/)

**Comment by Alecton4** [comment]
It's caused by a submodule from OpenSearch, not really related to the language server.
