### ISSUE TITLE
Cleaning workspace modifies source files

### ISSUE THREAD

**Issue by anthonyvdotbe** [oracle/javavscode#58]
When I do `Clean Workspace` (in an attempt to [have error reporting catch up](https://github.com/oracle/javavscode/issues/49)), sometimes my source files are modified. I have already noticed the same behavior when editing source files outside of VS Code (e.g. formatting with google-java-format).

There's this in the logs:

```
java.lang.IndexOutOfBoundsException: Invalid line index=63 >= lineCount=35
	at org.netbeans.modules.editor.lib2.document.LineRootElement.getElement(LineRootElement.java:68)
	at org.openide.text.NbDocument$DocumentRenderer.run(NbDocument.java:898)
	at org.netbeans.editor.BaseDocument.render(BaseDocument.java:1406)
	at org.openide.text.NbDocument$DocumentRenderer.renderToInt(NbDocument.java:873)
	at org.openide.text.NbDocument.findLineOffset(NbDocument.java:176)
	at org.netbeans.modules.java.lsp.server.Utils.getOffset(Utils.java:340)
	at org.netbeans.modules.java.lsp.server.protocol.TextDocumentServiceImpl.lambda$didChange$33(TextDocumentServiceImpl.java:1648)
	at org.netbeans.editor.GuardedDocument.runAtomic(GuardedDocument.java:296)
	at org.openide.text.NbDocument.runAtomic(NbDocument.java:411)
	at org.netbeans.modules.java.lsp.server.protocol.TextDocumentServiceImpl.didChange(TextDocumentServiceImpl.java:1644)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
Caused: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
Caused: java.lang.RuntimeException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:152)
[catch] at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:220)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:187)
	at org.netbeans.modules.java.lsp.server.protocol.Server$ConsumeWithLookup$1.lambda$consume$0(Server.java:295)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
	at org.netbeans.modules.java.lsp.server.protocol.Server$ConsumeWithLookup$1.consume(Server.java:293)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMejava.lang.IndexOutOfBoundsException: Invalid line index=79 >= lineCount=35
	at org.netbeans.modules.editor.lib2.document.LineRootElement.getElement(LineRootElement.java:68)
	at org.openide.text.NbDocument$DocumentRenderer.run(NbDocument.java:898)
	at org.netbeans.editor.BaseDocument.render(BaseDocument.java:1406)
	at org.openide.text.NbDocument$DocumentRenderer.renderToInt(NbDocument.java:873)
	at org.openide.text.NbDocument.findLineOffset(NbDocument.java:176)
	at org.netbeans.modules.java.lsp.server.Utils.getOffset(Utils.java:340)
	at org.netbeans.modules.java.lsp.server.protocol.TextDocumentServiceImpl.lambda$didChange$33(TextDocumentServiceImpl.java:1648)
	at org.netbeans.editor.GuardedDocument.runAtomic(GuardedDocument.java:296)
	at org.openide.text.NbDocument.runAtomic(NbDocument.java:411)
	at org.netbeans.modules.java.lsp.server.protocol.TextDocumentServiceImpl.didChange(TextDocumentServiceImpl.java:1644)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
Caused: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
Caused: java.lang.RuntimeException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:152)
[catch] at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:220)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:187)
	at org.netbeans.modules.java.lsp.server.protocol.Server$ConsumeWithLookup$1.lambda$consume$0(Server.java:295)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
	at org.netbeans.modules.java.lsp.server.protocol.Server$ConsumeWithLookup$1.consume(Server.java:293)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.rjava.lang.IndexOutOfBoundsException: Invalid line index=63 >= lineCount=35
	at org.netbeans.modules.editor.lib2.document.LineRootElement.getElement(LineRootElement.java:68)
	at org.openide.text.NbDocument$DocumentRenderer.run(NbDocument.java:898)
	at org.netbeans.editor.BaseDocument.render(BaseDocument.java:1406)
	at org.openide.text.NbDocument$DocumentRenderer.renderToInt(NbDocument.java:873)
	at org.openide.text.NbDocument.findLineOffset(NbDocument.java:176)
	at org.netbeans.modules.java.lsp.server.Utils.getOffset(Utils.java:340)
	at org.netbeans.modules.java.lsp.server.protocol.TextDocumentServiceImpl.lambda$didChange$33(TextDocumentServiceImpl.java:1648)
	at org.netbeans.editor.GuardedDocument.runAtomic(GuardedDocument.java:296)
	at org.openide.text.NbDocument.runAtomic(NbDocument.java:411)
	at org.netbeans.modules.java.lsp.server.protocol.TextDocumentServiceImpl.didChange(TextDocumentServiceImpl.java:1644)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
Caused: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
Caused: java.lang.RuntimeException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:152)
[catch] at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:220)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:187)
	at org.netbeans.modules.java.lsp.server.protocol.Server$ConsumeWithLookup$1.lambda$consume$0(Server.java:295)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
	at org.netbeans.modules.java.lsp.server.protocol.Server$ConsumeWithLookup$1.consume(Server.java:293)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
```

**Comment by singh-akhilesh** [comment]
We weren't able to reproduce the behavior with the information currently available, so we're going to close this issue for now.
